# Generated by Django 2.2.5 on 2019-09-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('runtime', models.IntegerField()),
                ('genre', models.CharField(max_length=128)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=64)),
                ('country_of_production', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_relase', models.DateField()),
                ('date_of_premiere', models.DateField()),
                ('dvd_premiere', models.DateField()),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=64)),
                ('writer', models.TextField(max_length=512)),
                ('actors', models.TextField(max_length=512)),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=32)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='MarketingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_office', models.IntegerField()),
                ('production', models.CharField(max_length=64)),
                ('website', models.URLField()),
                ('poster', models.URLField()),
                ('restrictions_ratings', models.CharField(max_length=32)),
                ('awards', models.TextField()),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'MarketingInfo',
                'verbose_name_plural': 'MarketingInfos',
            },
        ),
        migrations.CreateModel(
            name='ImdbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=12)),
                ('metascore', models.IntegerField()),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'ImdbInfo',
                'verbose_name_plural': 'ImdbInfos',
            },
        ),
    ]
