# Generated by Django 2.2.5 on 2019-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdbinfo',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='marketinginfo',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
