# Generated by Django 2.2.5 on 2019-09-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190919_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdbinfo',
            old_name='imdb_id',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='imdbinfo',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='imdbinfo',
            old_name='imdb_votes',
            new_name='imdbvotes',
        ),
        migrations.RenameField(
            model_name='marketinginfo',
            old_name='box_office',
            new_name='boxoffice',
        ),
        migrations.RenameField(
            model_name='marketinginfo',
            old_name='restrictions_ratings',
            new_name='rated',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country_of_production',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='content_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='date_of_premiere',
            new_name='dvd',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='dvd_premiere',
            new_name='relased',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='year_of_relase',
            new_name='year',
        ),
    ]
