# Generated by Django 2.2.5 on 2019-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190919_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=24),
        ),
    ]
