# Generated by Django 2.2.5 on 2019-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190919_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='relased',
            new_name='released',
        ),
        migrations.AlterField(
            model_name='marketinginfo',
            name='boxoffice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
